Update homework

diff --git a/Artur_Badalyan/Day2/dateScript b/Artur_Badalyan/Day2/dateScript
--- a/Artur_Badalyan/Day2/dateScript
+++ b/Artur_Badalyan/Day2/dateScript
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+echo "Please write 1 parm one of the following options : month,day,week,year,hour,minute,second"
+echo "Please write 2 parm number"
+
+nm='[0-9]'
+if ! [[ $2 =~ $nm ]] ; then
+   echo "error: 2 params not a number" >&2; exit 1
+fi
+
 
 case $1 in
     "month" )
@@ -22,7 +30,9 @@ case $1 in
           ;;
     "second" )
           echo $(date +"Year: %Y, Month: %m, Day: %d TIME: %T" -d "+$2 second")
-          ;;      
+          ;;
+        *)
+          echo "Please write one of the following options : month,day,week,year,hour,minute,second"      
 esac          
 
 
